[tool.poetry]
name = "plutus"
version = "0.1.0"
description = ""
authors = ["Brendan Truong <btruong413@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
